apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: new-app-devfile-sample-abae-sample
  namespace: sbudhwar-1-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/redhat-appstudio/user-workload@sha256:e504be911953f15959290b5d1f523d8314663529576468b92d3360896d22da55
        name: container-image
        resources: {}
status: {}
