apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: new-app
    appstudio.openshift.io/component: new-app-devfile-sample-abae-sample
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: new-app-devfile-sample-abae-sample
  namespace: sbudhwar-1-tenant
spec:
  url: https://github.com/nodeshift-starters/devfile-sample
